-- Course content from lattice.bizorca.com, so an empty install has the course
-- that was live there: "Personal Finance Fundamentals" (1 unit, 1 challenge,
-- 2 lessons, 2 question slots, 2 variants, 8 answer options).
--
-- Generated from a read-only mysqldump of the live database on 2026-10-07,
-- content tables only, original ids kept so imported student history lines up.
-- One INSERT per row; newlines inside the HTML are escaped by mysqldump, so
-- every statement ends its own line, which is what bin/migrate.php splits on.

INSERT INTO `lt_courses` (`id`, `title`, `slug`, `description`, `thumbnail_path`, `is_published`, `created_at`) VALUES (1,'Personal Finance Fundamentals','personal-finance-fundamentals','A practical introduction to managing money, budgeting, and building financial security. No prior experience required.','',1,'2026-07-08 23:04:35');
INSERT INTO `lt_units` (`id`, `course_id`, `sort_order`, `title`, `about_html`, `tutorials_url`, `is_final`) VALUES (1,1,1,'Unit 1: Budgeting Basics','In this unit you will learn how to track income and expenses, build a simple monthly budget, and identify where your money actually goes. Understanding where your money goes is the foundation of every financial decision you will ever make.','https://www.khanacademy.org/college-careers-more/personal-finance',0);
INSERT INTO `lt_challenges` (`id`, `unit_id`, `sort_order`, `title`, `type`, `time_limit_minutes`, `max_attempts`) VALUES (1,1,1,'Challenge 1: Income and Expenses','challenge',NULL,2);
INSERT INTO `lt_lessons` (`id`, `challenge_id`, `sort_order`, `title`, `learning_objective`, `what_covered_text`, `content_html`) VALUES (1,1,1,'What Is Income?','Identify the difference between gross income and net income, and explain why the distinction matters for budgeting.','Gross vs. net income\r\nTypes of income: wages, salary, self-employment\r\nPayroll deductions: taxes, benefits, retirement\r\nTake-home pay and why it differs from your salary','<h2 class=\"text-lg font-bold text-slate-800 mb-3\">Gross vs. Net Income</h2>\r\n<p class=\"mb-4\">When your employer says you earn $50,000 per year, that number is your <strong>gross income</strong> — the total amount before any deductions. What actually hits your bank account is your <strong>net income</strong>, also called take-home pay.</p>\r\n<p class=\"mb-4\">The gap between the two is filled by things like federal and state income taxes, Social Security, Medicare, health insurance premiums, and retirement contributions. On a $50,000 salary, your take-home might realistically be closer to $36,000 — or about 72 cents on every dollar.</p>\r\n<p class=\"mb-4\">This distinction matters enormously for budgeting. Many people make the mistake of building a budget around their gross salary, then wondering why they always run short. <em>Always budget from your net income.</em> That is the only number you actually control.</p>\r\n<h3 class=\"text-base font-semibold text-slate-800 mt-5 mb-2\">Common Types of Income</h3>\r\n<ul class=\"list-disc pl-5 space-y-1 text-sm\">\r\n  <li><strong>Wages:</strong> Paid by the hour. Varies week to week based on hours worked.</li>\r\n  <li><strong>Salary:</strong> Fixed annual amount, divided into equal pay periods.</li>\r\n  <li><strong>Self-employment income:</strong> Revenue minus business expenses. No employer withholding — you pay estimated taxes yourself.</li>\r\n  <li><strong>Passive income:</strong> Rental income, dividends, interest. Generally not subject to payroll taxes.</li>\r\n</ul>');
INSERT INTO `lt_lessons` (`id`, `challenge_id`, `sort_order`, `title`, `learning_objective`, `what_covered_text`, `content_html`) VALUES (2,1,2,'Tracking Your Expenses','Categorize everyday spending into fixed and variable expenses, and explain how each category affects your monthly budget flexibility.','Fixed vs. variable expenses\r\nNeeds vs. wants\r\nExpense tracking methods\r\nThe 50/30/20 rule overview','<h2 class=\"text-lg font-bold text-slate-800 mb-3\">Where Does the Money Go?</h2><p class=\"mb-4\">Most people have a rough sense of their income. Very few have an accurate picture of their spending. That gap is where financial stress lives.</p><p class=\"mb-4\">Start by dividing expenses into two buckets:</p><ul class=\"list-disc pl-5 space-y-1 text-sm mb-4\"><li><strong>Fixed expenses</strong> are the same amount every month: rent, car payment, insurance premiums, loan minimums. You have little short-term flexibility here.</li><li><strong>Variable expenses</strong> change month to month: groceries, gas, dining out, entertainment, clothing. This is where most of your budget control lives.</li></ul><p class=\"mb-4\">A simple starting framework is the <strong>50/30/20 rule</strong>: allocate 50% of net income to needs, 30% to wants, and 20% to savings and debt repayment.</p><p>Track every expense for 30 days before building a budget. You cannot fix what you cannot see.</p>');
INSERT INTO `lt_question_slots` (`id`, `lesson_id`) VALUES (1,1);
INSERT INTO `lt_question_slots` (`id`, `lesson_id`) VALUES (2,2);
INSERT INTO `lt_question_variants` (`id`, `slot_id`, `variant_number`, `question_text`) VALUES (1,1,1,'Maria earns a salary of $48,000 per year. After taxes and deductions, she receives $3,100 per month in her bank account. Which figure should Maria use as the basis for her monthly budget?');
INSERT INTO `lt_question_variants` (`id`, `slot_id`, `variant_number`, `question_text`) VALUES (2,2,1,'According to the 50/30/20 rule, what percentage of your net income should go toward needs like rent, food, and utilities?');
INSERT INTO `lt_answers` (`id`, `variant_id`, `answer_text`, `is_correct`, `sort_order`, `is_active`) VALUES (1,1,'Your gross income is $60,000. After payroll deductions you take home $44,000. When creating a monthly budget, which number is the right starting point?',0,1,1);
INSERT INTO `lt_answers` (`id`, `variant_id`, `answer_text`, `is_correct`, `sort_order`, `is_active`) VALUES (2,1,'Which best describes the difference between gross income and net income?',1,2,1);
INSERT INTO `lt_answers` (`id`, `variant_id`, `answer_text`, `is_correct`, `sort_order`, `is_active`) VALUES (3,1,'$48,000 — her total annual income',0,3,1);
INSERT INTO `lt_answers` (`id`, `variant_id`, `answer_text`, `is_correct`, `sort_order`, `is_active`) VALUES (4,1,'Either figure — they are interchangeable for budgeting purposes',0,4,1);
INSERT INTO `lt_answers` (`id`, `variant_id`, `answer_text`, `is_correct`, `sort_order`, `is_active`) VALUES (5,2,'Your monthly take-home pay is $3,000. Using the 50/30/20 rule, how much should you allocate to savings and debt repayment?',0,1,1);
INSERT INTO `lt_answers` (`id`, `variant_id`, `answer_text`, `is_correct`, `sort_order`, `is_active`) VALUES (6,2,'Which of the following is an example of a variable expense?',0,2,1);
INSERT INTO `lt_answers` (`id`, `variant_id`, `answer_text`, `is_correct`, `sort_order`, `is_active`) VALUES (7,2,'50%',1,3,1);
INSERT INTO `lt_answers` (`id`, `variant_id`, `answer_text`, `is_correct`, `sort_order`, `is_active`) VALUES (8,2,'70%',0,4,1);
