<?php
// Document viewer — opens generated HTML in a clean print-ready page.
require __DIR__ . '/_bootstrap.php';
requireLogin();

$user = getCurrentUser();
$db   = getDB();

$docId = (int)($_GET['id'] ?? 0);
if (!$docId) {
    header('Location: ' . url('/documents.php'));
    exit;
}

$stmt = $db->prepare('SELECT * FROM cw_documents WHERE id = ? LIMIT 1');
$stmt->execute([$docId]);
$doc = $stmt->fetch();

if (!$doc) {
    setFlash('error', 'Document not found.');
    header('Location: ' . url('/documents.php'));
    exit;
}

// Access control: verify the user owns this case or is coordinator/admin
$case = null;
if ($user['role'] === 'client') {
    $userCase = getUserCase((int)$user['id']);
    if (!$userCase || (int)$userCase['id'] !== (int)$doc['case_id']) {
        setFlash('error', 'Access denied.');
        header('Location: ' . url('/documents.php'));
        exit;
    }
    $case = $userCase;
} elseif (isCoordinator() || isAdmin()) {
    $stmt = $db->prepare(
        'SELECT cw_cases.*, cw_businesses.name AS business_name
         FROM cw_cases
         JOIN cw_businesses ON cw_businesses.id = cw_cases.business_id
         WHERE cw_cases.id = ? LIMIT 1'
    );
    $stmt->execute([$doc['case_id']]);
    $case = $stmt->fetch();
    if (!$case) {
        setFlash('error', 'Document not found.');
        header('Location: ' . url('/coordinator.php'));
        exit;
    }
    // Coordinator must be assigned
    if (!isAdmin() && (int)$case['coordinator_id'] !== (int)getCurrentUserId()) {
        setFlash('error', 'Access denied.');
        header('Location: ' . url('/coordinator.php'));
        exit;
    }
} else {
    header('Location: ' . url('/dashboard.php'));
    exit;
}

$docLabels = [
    'articles_of_incorporation' => 'Articles of Incorporation',
    'bylaws'                    => 'Cooperative Bylaws',
    'operating_agreement'       => 'Operating Agreement',
    'membership_agreement'      => 'Membership Agreement',
    'purchase_agreement'        => 'Business Purchase Agreement',
    'seller_note'               => 'Seller Promissory Note',
    'membership_certificate'    => 'Membership Certificate',
    'patronage_policy'          => 'Patronage Dividend Policy',
];
$docTitle = $docLabels[$doc['doc_type']] ?? ucwords(str_replace('_', ' ', $doc['doc_type']));
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= h($docTitle) ?> — CoopConvert</title>
    <style>
        body { font-family: Georgia, 'Times New Roman', serif; max-width: 780px; margin: 0 auto; padding: 2rem 1.5rem 4rem; color: #1a1a1a; line-height: 1.7; }
        h1, h2, h3 { font-family: system-ui, sans-serif; }
        @media print { .no-print { display: none !important; } body { padding: 0; } }
        .doc-meta { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 0.75rem 1rem; margin-bottom: 2rem; font-family: system-ui, sans-serif; font-size: 0.8rem; color: #166534; }
        .disclaimer { background: #fffbeb; border: 1px solid #fcd34d; border-radius: 8px; padding: 0.75rem 1rem; margin-bottom: 2rem; font-family: system-ui, sans-serif; font-size: 0.8rem; color: #92400e; }
        .doc-actions { font-family: system-ui, sans-serif; display: flex; gap: 1rem; margin-bottom: 2rem; }
        .doc-actions a, .doc-actions button { padding: 0.4rem 1rem; border-radius: 6px; font-size: 0.85rem; font-weight: 600; cursor: pointer; text-decoration: none; }
        .btn-print { background: #047857; color: white; border: none; }
        .btn-back { background: #f3f4f6; color: #374151; }
    </style>
</head>
<body>

<div class="no-print doc-actions">
    <a href="javascript:history.back()" class="btn-back">&larr; Back</a>
    <button class="btn-print" onclick="window.print()">Print / Save as PDF</button>
</div>

<div class="no-print doc-meta">
    <strong>Document:</strong> <?= h($docTitle) ?> &nbsp;&middot;&nbsp;
    <strong>Case:</strong> <?= h($case['business_name']) ?> &nbsp;&middot;&nbsp;
    <strong>Generated:</strong> <?= h(date('F j, Y g:ia', strtotime($doc['created_at']))) ?>
</div>

<div class="no-print disclaimer">
    <strong>Educational use only.</strong> This document is a template generated by CoopConvert and is not a substitute for legal advice. Have a Washington-licensed cooperative attorney review before filing or executing any agreements.
</div>

<?= $doc['rendered_html'] ?>

</body>
</html>
