-- 019 — The video production queue.
--
-- One row per short personal-finance video (5-15 minutes, one core idea),
-- seeded with the 100-topic bite-size curriculum built 2026-10-06 from the
-- class series and the Personal Finance Brain. Scripts are written in a Claude
-- Code session from the brain's trusted sources (on the subscription, like
-- extraction and weekly posts) and filed with `cli.php video-import`, which
-- `worker/video_push.py` drives. Nothing here calls a model.
--
-- `status` is the production pipeline Jassen moves a video through by hand:
-- topic -> scripted -> approved -> recorded -> edited -> published, or skipped.
-- `sources` keeps the brain citations the script rests on, so a claim can be
-- traced before recording; `notes` holds what must be updated or decided first.

CREATE TABLE IF NOT EXISTS video_scripts (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  number       SMALLINT UNSIGNED NOT NULL,
  part_no      TINYINT UNSIGNED NOT NULL,
  part_title   VARCHAR(80) NOT NULL,
  topic        VARCHAR(255) NOT NULL,
  slug         VARCHAR(100) NOT NULL,
  status       ENUM('topic','scripted','approved','recorded','edited','published','skipped')
               NOT NULL DEFAULT 'topic',
  title        VARCHAR(255) NULL,
  script       MEDIUMTEXT NULL,
  on_screen    TEXT NULL,
  sources      TEXT NULL,
  notes        TEXT NULL,
  words        SMALLINT UNSIGNED NULL,
  runtime_min  TINYINT UNSIGNED NULL,
  model        VARCHAR(40) NULL,
  scripted_at  DATETIME NULL,
  video_url    VARCHAR(500) NULL,
  published_at DATE NULL,
  my_notes     TEXT NULL,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_video_number (number),
  KEY ix_video_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO video_scripts (number, part_no, part_title, topic, slug) VALUES
(1,1,'Money Mindset','Your money story: the lessons you absorbed about money growing up, and how they still steer you','your-money-story-the-lessons-you-absorbed-about-money-growing-up-and-how-they-st'),
(2,1,'Money Mindset','Money scripts: common beliefs (money is bad, more money will fix it, money is status) and how to spot yours','money-scripts-common-beliefs-money-is-bad-more-money-will-fix-it-money-is-status'),
(3,1,'Money Mindset','Behavior beats knowledge: why knowing what to do isn''t the same as doing it','behavior-beats-knowledge-why-knowing-what-to-do-isn-t-the-same-as-doing-it'),
(4,1,'Money Mindset','Values first: goals tell you what, values tell you why','values-first-goals-tell-you-what-values-tell-you-why'),
(5,1,'Money Mindset','From values to intentions: turning what matters into a direction for your money','from-values-to-intentions-turning-what-matters-into-a-direction-for-your-money'),
(6,1,'Money Mindset','SMART goals that actually stick: specific, measurable, achievable, relevant, time-bound','smart-goals-that-actually-stick-specific-measurable-achievable-relevant-time-bou'),
(7,1,'Money Mindset','Pricing things in hours of your life: what that purchase really costs','pricing-things-in-hours-of-your-life-what-that-purchase-really-costs'),
(8,1,'Money Mindset','Defining "enough": why the finish line keeps moving, and how to set one','defining-enough-why-the-finish-line-keeps-moving-and-how-to-set-one'),
(9,2,'Spending Plan and Cash Flow','Track before you plan: the one-week spending diary','track-before-you-plan-the-one-week-spending-diary'),
(10,2,'Spending Plan and Cash Flow','Needs, wants and obligations: the most useful three-way split in personal finance','needs-wants-and-obligations-the-most-useful-three-way-split-in-personal-finance'),
(11,2,'Spending Plan and Cash Flow','Save, share, spend: the three jobs every dollar can do','save-share-spend-the-three-jobs-every-dollar-can-do'),
(12,2,'Spending Plan and Cash Flow','Building a spending plan that reads zero, positive or negative','building-a-spending-plan-that-reads-zero-positive-or-negative'),
(13,2,'Spending Plan and Cash Flow','Zero-based budgeting: give every dollar a job','zero-based-budgeting-give-every-dollar-a-job'),
(14,2,'Spending Plan and Cash Flow','Week-by-week cash flow: why monthly budgets fail when bills and paydays don''t line up','week-by-week-cash-flow-why-monthly-budgets-fail-when-bills-and-paydays-don-t-lin'),
(15,2,'Spending Plan and Cash Flow','Irregular and seasonal expenses: the bills that ambush a good budget','irregular-and-seasonal-expenses-the-bills-that-ambush-a-good-budget'),
(16,2,'Spending Plan and Cash Flow','When money is short: pay by consequence, keeping a roof, utilities and transportation first','when-money-is-short-pay-by-consequence-keeping-a-roof-utilities-and-transportati'),
(17,2,'Spending Plan and Cash Flow','Two ways to close a gap: earn more or spend less, and which to try first','two-ways-to-close-a-gap-earn-more-or-spend-less-and-which-to-try-first'),
(18,2,'Spending Plan and Cash Flow','The ten-minute weekly money check-in','the-ten-minute-weekly-money-check-in'),
(19,3,'Income and Taxes','Gross pay, net pay and everything in between','gross-pay-net-pay-and-everything-in-between'),
(20,3,'Income and Taxes','How to read your pay stub, line by line','how-to-read-your-pay-stub-line-by-line'),
(21,3,'Income and Taxes','FICA explained: what Social Security and Medicare take out of your check','fica-explained-what-social-security-and-medicare-take-out-of-your-check'),
(22,3,'Income and Taxes','Employee or contractor: W-2 versus 1099 and why it changes your taxes','employee-or-contractor-w-2-versus-1099-and-why-it-changes-your-taxes'),
(23,3,'Income and Taxes','The W-4: setting your withholding on purpose','the-w-4-setting-your-withholding-on-purpose'),
(24,3,'Income and Taxes','A big refund is not a bonus: it''s your money, returned late and interest-free','a-big-refund-is-not-a-bonus-it-s-your-money-returned-late-and-interest-free'),
(25,3,'Income and Taxes','Your tax return in one line: income, adjustments, deductions, credits, refund or balance due','your-tax-return-in-one-line-income-adjustments-deductions-credits-refund-or-bala'),
(26,3,'Income and Taxes','Deductions versus credits: why a credit is worth more than a deduction','deductions-versus-credits-why-a-credit-is-worth-more-than-a-deduction'),
(27,3,'Income and Taxes','Free tax help: VITA, AARP Tax-Aide and IRS Free File','free-tax-help-vita-aarp-tax-aide-and-irs-free-file'),
(28,3,'Income and Taxes','Owing the IRS and can''t pay: file anyway, then look at payment plans','owing-the-irs-and-can-t-pay-file-anyway-then-look-at-payment-plans'),
(29,4,'Banking and Protecting Your Accounts','Banks versus credit unions: what''s different and what matters','banks-versus-credit-unions-what-s-different-and-what-matters'),
(30,4,'Banking and Protecting Your Accounts','Deposit insurance: how FDIC and NCUA coverage protects your money, and what it doesn''t cover','deposit-insurance-how-fdic-and-ncua-coverage-protects-your-money-and-what-it-doe'),
(31,4,'Banking and Protecting Your Accounts','Choosing a checking account: the fee schedule questions to ask first','choosing-a-checking-account-the-fee-schedule-questions-to-ask-first'),
(32,4,'Banking and Protecting Your Accounts','Overdrafts: how they happen, what they cost, and how to opt out','overdrafts-how-they-happen-what-they-cost-and-how-to-opt-out'),
(33,4,'Banking and Protecting Your Accounts','Banking history reports: ChexSystems and what to do if you''ve been turned away','banking-history-reports-chexsystems-and-what-to-do-if-you-ve-been-turned-away'),
(34,4,'Banking and Protecting Your Accounts','Prepaid cards, payment apps and check cashers: the true cost of banking alternatives','prepaid-cards-payment-apps-and-check-cashers-the-true-cost-of-banking-alternativ'),
(35,4,'Banking and Protecting Your Accounts','Automation that protects you: direct deposit, alerts and autopay','automation-that-protects-you-direct-deposit-alerts-and-autopay'),
(36,4,'Banking and Protecting Your Accounts','Payment app scams: why "send money to a stranger" is almost never safe','payment-app-scams-why-send-money-to-a-stranger-is-almost-never-safe'),
(37,5,'Saving','Pay yourself first, and automate it','pay-yourself-first-and-automate-it'),
(38,5,'Saving','Finding money to save: small cuts that add up','finding-money-to-save-small-cuts-that-add-up'),
(39,5,'Saving','The emergency fund: why it prevents new debt','the-emergency-fund-why-it-prevents-new-debt'),
(40,5,'Saving','How big should your emergency fund be? Starter fund versus three to six months','how-big-should-your-emergency-fund-be-starter-fund-versus-three-to-six-months'),
(41,5,'Saving','Where to keep savings: savings accounts, money market accounts, CDs and high-yield options','where-to-keep-savings-savings-accounts-money-market-accounts-cds-and-high-yield-'),
(42,5,'Saving','Compound interest: interest on your interest','compound-interest-interest-on-your-interest'),
(43,5,'Saving','The Rule of 72: how fast money doubles','the-rule-of-72-how-fast-money-doubles'),
(44,5,'Saving','Saving for big goals: divide the cost by the time you have','saving-for-big-goals-divide-the-cost-by-the-time-you-have'),
(45,6,'Credit','Your credit report: what''s on it and who looks at it','your-credit-report-what-s-on-it-and-who-looks-at-it'),
(46,6,'Credit','Getting your free credit reports, and spotting the imposter sites','getting-your-free-credit-reports-and-spotting-the-imposter-sites'),
(47,6,'Credit','How to read a credit report, section by section','how-to-read-a-credit-report-section-by-section'),
(48,6,'Credit','Finding and disputing errors yourself, in writing','finding-and-disputing-errors-yourself-in-writing'),
(49,6,'Credit','Credit scores: the five factors and how they''re weighted','credit-scores-the-five-factors-and-how-they-re-weighted'),
(50,6,'Credit','Credit utilization: how much of your limit to use','credit-utilization-how-much-of-your-limit-to-use'),
(51,6,'Credit','Building credit from scratch: secured cards, credit-builder loans and authorized users','building-credit-from-scratch-secured-cards-credit-builder-loans-and-authorized-u'),
(52,6,'Credit','Repairing credit after a rough patch: what works and how long it takes','repairing-credit-after-a-rough-patch-what-works-and-how-long-it-takes'),
(53,6,'Credit','Never pay for "credit repair": what those companies can''t legally do for you','never-pay-for-credit-repair-what-those-companies-can-t-legally-do-for-you'),
(54,7,'Debt','Debt versus credit: the difference, and why it matters','debt-versus-credit-the-difference-and-why-it-matters'),
(55,7,'Debt','Installment versus revolving debt: how each one works','installment-versus-revolving-debt-how-each-one-works'),
(56,7,'Debt','The minimum payment trap: how $5,000 on a card becomes decades of payments','the-minimum-payment-trap-how-5-000-on-a-card-becomes-decades-of-payments'),
(57,7,'Debt','Know your debts: listing every balance, rate, payment and due date','know-your-debts-listing-every-balance-rate-payment-and-due-date'),
(58,7,'Debt','Snowball or avalanche: smallest balance first or highest rate first','snowball-or-avalanche-smallest-balance-first-or-highest-rate-first'),
(59,7,'Debt','Making extra payments count: which debt gets the extra dollar','making-extra-payments-count-which-debt-gets-the-extra-dollar'),
(60,7,'Debt','Debt collectors: your rights under the Fair Debt Collection Practices Act','debt-collectors-your-rights-under-the-fair-debt-collection-practices-act'),
(61,7,'Debt','Medical debt: why it''s different and how to negotiate it','medical-debt-why-it-s-different-and-how-to-negotiate-it'),
(62,7,'Debt','Student loans: federal repayment options and what to watch for','student-loans-federal-repayment-options-and-what-to-watch-for'),
(63,7,'Debt','Payday loans, title loans and rent-to-own: the costliest money there is','payday-loans-title-loans-and-rent-to-own-the-costliest-money-there-is'),
(64,7,'Debt','Debt settlement, consolidation and bankruptcy: when they help and when they hurt','debt-settlement-consolidation-and-bankruptcy-when-they-help-and-when-they-hurt'),
(65,8,'Big Purchases and Housing','Buying a car: total cost of ownership, not just the monthly payment','buying-a-car-total-cost-of-ownership-not-just-the-monthly-payment'),
(66,8,'Big Purchases and Housing','Auto loans: loan length, interest and the upside-down trap','auto-loans-loan-length-interest-and-the-upside-down-trap'),
(67,8,'Big Purchases and Housing','What can you afford for housing? Three ways to find your number','what-can-you-afford-for-housing-three-ways-to-find-your-number'),
(68,8,'Big Purchases and Housing','Rent or buy: the real comparison, beyond "renting is throwing money away"','rent-or-buy-the-real-comparison-beyond-renting-is-throwing-money-away'),
(69,8,'Big Purchases and Housing','Renting smart: reading a lease, deposits and your tenant rights','renting-smart-reading-a-lease-deposits-and-your-tenant-rights'),
(70,8,'Big Purchases and Housing','Getting ready to buy a home: credit, savings, down payment and closing costs','getting-ready-to-buy-a-home-credit-savings-down-payment-and-closing-costs'),
(71,8,'Big Purchases and Housing','Mortgages explained: fixed versus adjustable, 15 versus 30 years, points and APR','mortgages-explained-fixed-versus-adjustable-15-versus-30-years-points-and-apr'),
(72,8,'Big Purchases and Housing','Shopping for a mortgage: comparing Loan Estimates and spotting red flags','shopping-for-a-mortgage-comparing-loan-estimates-and-spotting-red-flags'),
(73,9,'Insurance and Protecting What Matters','Insure what you can''t absorb, and self-insure the small things','insure-what-you-can-t-absorb-and-self-insure-the-small-things'),
(74,9,'Insurance and Protecting What Matters','Insurance basics: premiums, deductibles, coverage limits and exclusions','insurance-basics-premiums-deductibles-coverage-limits-and-exclusions'),
(75,9,'Insurance and Protecting What Matters','Auto insurance: liability, collision and comprehensive, and how to save','auto-insurance-liability-collision-and-comprehensive-and-how-to-save'),
(76,9,'Insurance and Protecting What Matters','Homeowners and renters insurance: what''s covered and what isn''t','homeowners-and-renters-insurance-what-s-covered-and-what-isn-t'),
(77,9,'Insurance and Protecting What Matters','Health insurance: plan types, the Marketplace, Medicaid and Medicare','health-insurance-plan-types-the-marketplace-medicaid-and-medicare'),
(78,9,'Insurance and Protecting What Matters','Life insurance: term versus whole, and how much you might need','life-insurance-term-versus-whole-and-how-much-you-might-need'),
(79,9,'Insurance and Protecting What Matters','Disability insurance: protecting your paycheck','disability-insurance-protecting-your-paycheck'),
(80,9,'Insurance and Protecting What Matters','Identity theft: prevention, plus the recovery steps (FTC report, fraud alert, credit freeze)','identity-theft-prevention-plus-the-recovery-steps-ftc-report-fraud-alert-credit-'),
(81,9,'Insurance and Protecting What Matters','Elder financial exploitation, and naming a trusted contact on your accounts','elder-financial-exploitation-and-naming-a-trusted-contact-on-your-accounts'),
(82,10,'Investing and Retirement','Saving versus investing: different jobs for different time horizons','saving-versus-investing-different-jobs-for-different-time-horizons'),
(83,10,'Investing and Retirement','Risk and return: why higher returns come with bumpier rides','risk-and-return-why-higher-returns-come-with-bumpier-rides'),
(84,10,'Investing and Retirement','Stocks, bonds and cash: the building blocks of every portfolio','stocks-bonds-and-cash-the-building-blocks-of-every-portfolio'),
(85,10,'Investing and Retirement','Diversification: don''t bet everything on one horse','diversification-don-t-bet-everything-on-one-horse'),
(86,10,'Investing and Retirement','Index funds: why low-cost, broad funds beat most professionals after costs','index-funds-why-low-cost-broad-funds-beat-most-professionals-after-costs'),
(87,10,'Investing and Retirement','Costs compound too: how a 1% fee eats your retirement','costs-compound-too-how-a-1-fee-eats-your-retirement'),
(88,10,'Investing and Retirement','Target date funds: the one-fund portfolio and how it works','target-date-funds-the-one-fund-portfolio-and-how-it-works'),
(89,10,'Investing and Retirement','Your behavior is the biggest risk: buying high, selling low, and how not to','your-behavior-is-the-biggest-risk-buying-high-selling-low-and-how-not-to'),
(90,10,'Investing and Retirement','Start early: why time is the one investing ingredient you can''t buy','start-early-why-time-is-the-one-investing-ingredient-you-can-t-buy'),
(91,10,'Investing and Retirement','Workplace retirement plans and the employer match','workplace-retirement-plans-and-the-employer-match'),
(92,10,'Investing and Retirement','Traditional or Roth: pay tax now or pay tax later','traditional-or-roth-pay-tax-now-or-pay-tax-later'),
(93,10,'Investing and Retirement','How much do you need to retire? Estimating your number','how-much-do-you-need-to-retire-estimating-your-number'),
(94,10,'Investing and Retirement','Social Security: how benefits are earned and when to claim','social-security-how-benefits-are-earned-and-when-to-claim'),
(95,10,'Investing and Retirement','Spending it down: drawing an income in retirement, and why dying with zero is a real goal','spending-it-down-drawing-an-income-in-retirement-and-why-dying-with-zero-is-a-re'),
(96,11,'The Bigger Picture','Inflation: why prices rise, and what it does to your savings and your debts','inflation-why-prices-rise-and-what-it-does-to-your-savings-and-your-debts'),
(97,11,'The Bigger Picture','Interest rates and the Fed: how a decision in Washington reaches your wallet','interest-rates-and-the-fed-how-a-decision-in-washington-reaches-your-wallet'),
(98,11,'The Bigger Picture','Choosing financial help: fiduciaries, coaches, counselors and how advisers get paid','choosing-financial-help-fiduciaries-coaches-counselors-and-how-advisers-get-paid'),
(99,11,'The Bigger Picture','"Guaranteed income" pitches: what weekly options income and other easy-money schemes leave out','guaranteed-income-pitches-what-weekly-options-income-and-other-easy-money-scheme'),
(100,11,'The Bigger Picture','Planning for incapacity: wills, powers of attorney, beneficiaries, and the people who may one day manage your money','planning-for-incapacity-wills-powers-of-attorney-beneficiaries-and-the-people-wh');
